import "./globals.css";
export const metadata = { title: 'v0-1773055465237-6o04u', description: 'Generated by v0' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}